import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "@/components/Menu";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "FactWise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="h-screen flex">
          {/* LEFT */}
          <div className="w-[15%] sm:w-[10%] lg:w-[5%] flex flex-col items-center p-4 bg-gray-200">
            <Link
              href="/"
              className="flex items-center justify-center lg:justify-start gap-2"
            >
              <Image
                src="/factwiseLogo.png"
                alt="logo"
                width={32}
                height={32}
              />
            </Link>
            <div className="flex-grow flex items-center justify-center">
              <Menu />
            </div>
          </div>
          {/* RIGHT */}
          <div className="w-[85%] sm:w-[90%] lg:w-[95%] bg-[#F7F8FA] flex flex-col">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
